const actionTypes = {
  'SET_USER': 'SET_USER',
  'FETCH_SETTINGS': 'FETCH_SETTINGS',
  'SET_TOKEN': 'SET_TOKEN',
  'SET_UPDATE_STATUS': 'SET_UPDATE_STATUS',


  'ADD_OPERATOR':        'ADD_OPERATOR',
  'ADD_NUMBER':        'ADD_NUMBER',

  'ADD_DECIMAL_POINT':        'ADD_DECIMAL_POINT',
  'INPUT_PERCENT':     'INPUT_PERCENT',
  'TOGGLE_SIGN':       'TOGGLE_SIGN',

  'RESET_CALCULATOR':  'RESET_CALCULATOR',
  'CALCULATE':         'CALCULATE',
}

export default actionTypes
